[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
build_flags = -std=gnu++17
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit SHT4x Library
  adafruit/Adafruit BusIO
  protocentral/ProtoCentral MAX30205 Body Temperature Sensor Library