[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
build_flags = -std=gnu++17
monitor_speed = 115200
build_src_filter = +<*> -<bench_diag.cpp>
lib_deps =
  adafruit/Adafruit SHT4x Library
  adafruit/Adafruit BusIO
  protocentral/ProtoCentral MAX30205 Body Temperature Sensor Library

[env:bench_diag]
extends = env:seeed_xiao_esp32s3
build_src_filter = +<bench_diag.cpp>

[env:bench_fsm]
extends = env:seeed_xiao_esp32s3
build_src_filter = +<*> -<bench_diag.cpp>
build_flags = ${env:seeed_xiao_esp32s3.build_flags} -DSSB_DEBUG_SERIAL_BUTTON
